-- 코드를 입력하세요
SELECT CART_ID
FROM CART_PRODUCTS
GROUP BY CART_ID
HAVING SUM(CASE WHEN LOWER(NAME) = "milk" THEN 1 ELSE 0 END) > 0
    AND SUM(CASE WHEN LOWER(NAME) = "yogurt" THEN 1 ELSE 0 END) > 0
ORDER BY CART_ID;
