-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I ON I.ANIMAL_ID=O.ANIMAL_ID AND I.SEX_UPON_INTAKE LIKE "Intact%"
WHERE I.ANIMAL_ID IS NOT NULL
    AND O.SEX_UPON_OUTCOME NOT LIKE "Intact%"
ORDER BY O.ANIMAL_ID;
